apiVersion: v1
kind: Service
metadata:
  name: api-acumux
spec:
  ports:
    - port: 3443
      protocol: TCP
      targetPort: 3443
  clusterIP: None  # or omit it for a virtual IP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: api-acumux
subsets:
  - addresses:
      - ip: 192.168.64.1
    ports:
      - port: 3443
        protocol: TCP