# yaml-language-server: $schema=/Users/marcusheese/src/acuvity/backend/pkgs/api/backend/jsonschema/import.json

label: mcp-providers

providers:
  - name: mcp-demo-agent
    status: Stable
    friendlyName: MCP Demo - Agent
    category: App
    description: "The agent application of the MCP chatbot demo"
    hosts:
      - name: mcp-demo-agent.mcp-demo.svc.cluster.local
      - name: mcp-demo-agent.mcp-demo
      - name: mcp-demo-agent
    extractors:
      - def:
          name: chat/request/message
          type: Input
          path: "/api/v1/chat"
          method: Post
          script: |-
            function extract()
              body = json.decode(input.body())
              return {
                annotations = { conversation_id = body.conversation_id },
                extractions = { content = body.message },
              }
            end
      - def:
          name: chat/response/message
          type: Output
          path: "/api/v1/chat"
          method: Post
          script: |-
            function extract()
              body = json.decode(input.body())
              return {
                annotations = { conversation_id = body.conversation_id },
                extractions = { content = body.message },
              }
            end
  - name: mcp-demo-mcp-brave-search
    status: Stable
    friendlyName: MCP Demo - MCP Server - Brave Search
    category: App
    description: "MCP server for Brave Search"
    analyzeOutput: true
    hosts:
      - name: mcp-server-brave-search.mcp-demo.svc.cluster.local
      - name: mcp-server-brave-search.mcp-demo
      - name: mcp-server-brave-search
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-fetch
    status: Stable
    friendlyName: MCP Demo - MCP Server - Fetch
    category: App
    description: "MCP server for Fetch"
    analyzeOutput: true
    hosts:
      - name: mcp-server-fetch.mcp-demo.svc.cluster.local
      - name: mcp-server-fetch.mcp-demo
      - name: mcp-server-fetch
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-github
    status: Stable
    friendlyName: MCP Demo - MCP Server - GitHub
    category: App
    description: "MCP server for GitHub"
    analyzeOutput: true
    hosts:
      - name: mcp-server-github.mcp-demo.svc.cluster.local
      - name: mcp-server-github.mcp-demo
      - name: mcp-server-github
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-memory
    status: Stable
    friendlyName: MCP Demo - MCP Server - Memory
    category: App
    description: "MCP server for Memory"
    analyzeOutput: true
    hosts:
      - name: mcp-server-memory.mcp-demo.svc.cluster.local
      - name: mcp-server-memory.mcp-demo
      - name: mcp-server-memory
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-sequential-thinking
    status: Stable
    friendlyName: MCP Demo - MCP Server - Sequential Thinking
    category: App
    description: "MCP server for Sequential Thinking"
    analyzeOutput: true
    hosts:
      - name: mcp-server-sequential-thinking.mcp-demo.svc.cluster.local
      - name: mcp-server-sequential-thinking.mcp-demo
      - name: mcp-server-sequential-thinking
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-everything
    status: Stable
    friendlyName: MCP Demo - MCP Server - Everything
    category: App
    description: "MCP server for Everything"
    analyzeOutput: true
    hosts:
      - name: mcp-server-everything.mcp-demo.svc.cluster.local
      - name: mcp-server-everything.mcp-demo
      - name: mcp-server-everything
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-microsoft
    status: Stable
    friendlyName: MCP Demo - MCP Server - Microsoft
    category: App
    description: "MCP server Microsoft"
    analyzeOutput: true
    hosts:
      - name: mcp-server-microsoft.mcp-demo.svc.cluster.local
      - name: mcp-server-microsoft.mcp-demo
      - name: mcp-server-microsoft
    extractors:
      - ref: mcp/input
      - ref: mcp/output
  - name: mcp-demo-mcp-harness
    status: Stable
    friendlyName: MCP Demo - MCP Server - Harness
    category: App
    description: "MCP server for Harness"
    analyzeOutput: true
    hosts:
      - name: mcp-server-harness.mcp-demo.svc.cluster.local
      - name: mcp-server-harness.mcp-demo
      - name: mcp-server-harness
    extractors:
      - ref: mcp/input
      - ref: mcp/output
